name: Build nuxtjs app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Install dev dependencies.
        run: echo "Hello ${{secrets.MY_NAME}}"
