name: Build nuxtjs app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "Hello this is a step"
